[package]
name = "jamebot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serenity = { version = "0.11", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model", "framework", "standard_framework"] }
poise = "0.5.2"
tokio = { version = "1.21.2", features = ["macros", "signal", "rt-multi-thread"] }
openssl = { version = "0.10", features = ["vendored"] } # for cross compiling
tracing = "0.1.37"
execute = "0.2.11"
rand = "0.8.5"
reqwest = "0.11.13"
serde = "1.0.149"
chrono = "0.4.23"
